{"name": "test_query_results_cannot_be_retrieved_when_action_denied_for_gateway", "status": "skipped", "statusDetails": {"message": "XFAIL Bug https://neom.atlassian.net/browse/NEOS-3266 [BE] 500 error when user without product:consume permissions tries to list products or run statement (GET powerbi/products, POST powerbi/statement)\n\nrequests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://ivanh2.neosdata.cloud/api/consume/v2/powerbi/statement", "trace": "../../../Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/pytest_lazyfixture.py:39: in fill\n    _fillfixtures()\ntests/integration/api/consume/powerbi/conftest.py:18: in run_select_query\n    powerbi_query.run(query_data=new_data_product_v2.trino_table.name)\nharness/helpers/api/powerbi/consume_query.py:60: in run\n    response.raise_for_status()\n../../../Library/Caches/pypoetry/virtualenvs/neos-core-tests-UGE2DFwI-py3.10/lib/python3.10/site-packages/requests/models.py:1021: in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nE   requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://ivanh2.neosdata.cloud/api/consume/v2/powerbi/statement"}, "description": "\n        As a user\n        When I have `product:consume` action denied for gateway\n        And I retrieve query results\n        Then I get an error response\n        ", "attachments": [{"name": "log", "source": "2e93becb-b5d9-4401-bb5d-3cecbee70a1c-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "14e12171-b6f3-43ea-86da-8ae0f644842e-attachment.txt", "type": "text/plain"}], "start": 1698654770037, "stop": 1698654770037, "uuid": "7f813652-6a07-4241-aea7-b9082c5c4790", "historyId": "9fb6bb6a49281fdfef742c94392d8684", "testCaseId": "9fb6bb6a49281fdfef742c94392d8684", "fullName": "tests.integration.api.consume.powerbi.test_get_query_results.TestApiGetQueryResults#test_query_results_cannot_be_retrieved_when_action_denied_for_gateway", "labels": [{"name": "feature", "value": "Get query results"}, {"name": "parentSuite", "value": "[API] ConsumeQuery"}, {"name": "story", "value": "Query results cannot be retrieved when `product:consume` action denied for gateway"}, {"name": "tag", "value": "@pytest.mark.usefixtures('authenticate_neos_admin', 'create_product_1_v2', 'add_product_1_schema_v2', 'add_rows_to_product_1_table', 'create_data_product_v2', 'add_schema_v2', 'builder_set_product_1_as_input', 'builder_run', 'publish_data_product_v2', 'create_user', 'set_user_policy_type', 'allow_registry_product_consume_action', 'deny_product_consume_action', 'create_user_policy', 'authenticate_as_new_user', 'run_select_query')"}, {"name": "tag", "value": "@pytest.mark.xfail(reason='Bug https://neom.atlassian.net/browse/NEOS-3266 [BE] 500 error when user without product:consume permissions tries to list products or run statement (GET powerbi/products, POST powerbi/statement)')"}, {"name": "tag", "value": "access"}, {"name": "tag", "value": "negative"}, {"name": "tag", "value": "consume"}, {"name": "suite", "value": "test_get_query_results"}, {"name": "subSuite", "value": "TestApiGetQueryResults"}, {"name": "host", "value": "Is-MacBook-Pro.local"}, {"name": "thread", "value": "26202-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.integration.api.consume.powerbi.test_get_query_results"}]}