{"name": "test_query_results_cannot_be_retrieved[Not existing key]", "status": "passed", "description": "\n        As a user\n        When I retrieve query results incorrect data\n        Then I get an error response\n        ", "attachments": [{"name": "log", "source": "db035af0-c2d0-4d0e-9090-5ac5a817d03b-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "cfdbff5f-b46e-4df5-bfe2-62d9d3122737-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "key", "value": "'asentzaalg'"}, {"name": "expected_error", "value": "<harness.api.model.error.api_error.ApiError object at 0x10d41c310>"}], "start": 1698655193311, "stop": 1698655193348, "uuid": "5e7a0a06-9344-4846-b569-5cd7810601fa", "historyId": "511eda9fbaec5cfed5249ab8f66aa948", "testCaseId": "120e73d2e377017af9b514a4ef7282bf", "fullName": "tests.integration.api.consume.powerbi.test_get_query_results.TestApiGetQueryResults#test_query_results_cannot_be_retrieved", "labels": [{"name": "parentSuite", "value": "[API] ConsumeQuery"}, {"name": "story", "value": "Query results cannot be retrieved"}, {"name": "feature", "value": "Get query results"}, {"name": "tag", "value": "@pytest.mark.usefixtures('authenticate_neos_admin')"}, {"name": "tag", "value": "negative"}, {"name": "tag", "value": "consume"}, {"name": "suite", "value": "test_get_query_results"}, {"name": "subSuite", "value": "TestApiGetQueryResults"}, {"name": "host", "value": "Is-MacBook-Pro.local"}, {"name": "thread", "value": "26450-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.integration.api.consume.powerbi.test_get_query_results"}]}