{"name": "test_query_results_cannot_be_retrieved[Empty key]", "status": "passed", "description": "\n        As a user\n        When I retrieve query results incorrect data\n        Then I get an error response\n        ", "attachments": [{"name": "log", "source": "8a6bcaa5-7d57-40ab-88a9-9b1c55b079e4-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "31048238-0d77-412a-a1d4-c03cf4fa0832-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "key", "value": "' '"}, {"name": "expected_error", "value": "<harness.api.model.error.api_error.ApiError object at 0x1111302e0>"}], "start": 1698655193253, "stop": 1698655193301, "uuid": "9cd1b679-b253-4c3c-a556-b58907d3e0a3", "historyId": "7adefb992b06d83b134b101f625a1e4a", "testCaseId": "120e73d2e377017af9b514a4ef7282bf", "fullName": "tests.integration.api.consume.powerbi.test_get_query_results.TestApiGetQueryResults#test_query_results_cannot_be_retrieved", "labels": [{"name": "story", "value": "Query results cannot be retrieved"}, {"name": "feature", "value": "Get query results"}, {"name": "parentSuite", "value": "[API] ConsumeQuery"}, {"name": "tag", "value": "@pytest.mark.usefixtures('authenticate_neos_admin')"}, {"name": "tag", "value": "negative"}, {"name": "tag", "value": "consume"}, {"name": "suite", "value": "test_get_query_results"}, {"name": "subSuite", "value": "TestApiGetQueryResults"}, {"name": "host", "value": "Is-MacBook-Pro.local"}, {"name": "thread", "value": "26449-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.integration.api.consume.powerbi.test_get_query_results"}]}