{"name": "test_query_results_cannot_be_retrieved[Not existing key]", "status": "passed", "description": "\n        As a user\n        When I retrieve query results incorrect data\n        Then I get an error response\n        ", "attachments": [{"name": "log", "source": "2826d6f2-54d7-48a6-a8ac-b5ad03328bbe-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "33621e14-359b-4331-a091-efa6798b5213-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "key", "value": "'mpkrunsvrz'"}, {"name": "expected_error", "value": "<harness.api.model.error.api_error.ApiError object at 0x10f41c460>"}], "start": 1698654755006, "stop": 1698654755041, "uuid": "5665a710-30bb-4c1c-a7f4-b76328695d41", "historyId": "236d76ec24a7ca45bd9552e2c298c1c6", "testCaseId": "120e73d2e377017af9b514a4ef7282bf", "fullName": "tests.integration.api.consume.powerbi.test_get_query_results.TestApiGetQueryResults#test_query_results_cannot_be_retrieved", "labels": [{"name": "story", "value": "Query results cannot be retrieved"}, {"name": "feature", "value": "Get query results"}, {"name": "parentSuite", "value": "[API] ConsumeQuery"}, {"name": "tag", "value": "@pytest.mark.usefixtures('authenticate_neos_admin')"}, {"name": "tag", "value": "negative"}, {"name": "tag", "value": "consume"}, {"name": "suite", "value": "test_get_query_results"}, {"name": "subSuite", "value": "TestApiGetQueryResults"}, {"name": "host", "value": "Is-MacBook-Pro.local"}, {"name": "thread", "value": "26202-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.integration.api.consume.powerbi.test_get_query_results"}]}